# Generated by Django 3.2.16 on 2023-02-08 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone2',
        ),
    ]
