# Generated by Django 3.2.16 on 2023-02-08 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_phone2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='server',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='clients.server'),
            preserve_default=False,
        ),
    ]
