# Generated by Django 3.2.16 on 2023-02-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20230207_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
    ]
