# Generated by Django 3.2.16 on 2023-02-11 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
        ('clients', '0006_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.server'),
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
